function [F,S,g,psi,exactu,exactp,exactut]=tc2source(params,xend)
%Functions representations of F, S, g, psi, exactu, exactp, and exactut
    chi=@(y)sin(params.omegax * y);
    dchi=@(y)params.omegax*cos(params.omegax*y);
    d2chi=@(y)-(params.omegax^2)*sin(params.omegax*y);
    tau=@(m)sin(params.omegat*m);%.*sin(params.omegat*m);
    dtau=@(m)params.omegat*cos(params.omegat*m);
F=@(y,t)-(params.Uref*d2chi(y).*(params.Ha*tau(t)+...
    params.delta*params.Hv*(tau(t) - ...
    tau(t-params.deltat))/params.deltat)-params.Pref*tau(t).*dchi(y));
S=@(y,t)params.Uref*((tau(t) - ...
    tau(t-params.deltat))/params.deltat).*dchi(y)...
    -t.*params.Pref*d2chi(y).*tau(t);
g=@(t)params.Uref*dchi(xend)*(params.Ha*tau(t)+...
    params.delta*params.Hv*(tau(t) - ...
    tau(t-params.deltat))/params.deltat)...
    -params.Pref*tau(t)*chi(params.length);
psi=@(t)-t.*params.Pref*tau(t)*dchi(xend);
exactu=@(y,t)params.Uref*chi(y).*tau(t);
exactp=@(y,t)params.Pref*chi(y).*tau(t);
exactut=@(y,t)params.Uref*chi(y).*dtau(t);
end